name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ianwalter/puppeteer:2.0.0
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install
        run: pnpm i
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
